# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#home'
    weight: 100
  - name: Vita
    url: '#about'
    weight: 200
  - name: Research
    url: '#research'
    weight: 300
  - name: Teaching
    url: '#teaching'
    weight: 400
#  - name: Posts
#    url: '#posts'
#    weight: 201
#  - name: Projects
#    url: '#projects'
#    weight: 301
#  - name: Talks
#    url: '#talks'
#    weight: 401
#  - name: Publications
#    url: '#featured'
#    weight: 501
  - name: Other
    url: '#other'
    weight: 600
  - name: Contact
    url: '#contact'
    weight: 1000

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
